services:
  db:
    image: postgres:17.2-alpine3.21
    restart: always
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./.environment/local/nginx/server.conf:/etc/nginx/conf.d/default.conf
      - ./:/app/

  php_fpm:
    build: ./.environment/local/php
    environment:
      PHP_IDE_CONFIG: "serverName=test-task.dev"
    volumes:
      - ./:/app
      - ./.environment/local/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

volumes:
  postgres-data:
    driver: local
